# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeviseTokenAuth::Concerns::SetUserByToken`.
# Please instead update this file by running `bin/tapioca dsl DeviseTokenAuth::Concerns::SetUserByToken`.

module DeviseTokenAuth::Concerns::SetUserByToken
  mixes_in_class_methods ::DeviseTokenAuth::Controllers::Helpers::ClassMethods
end
